# Template: flake-parts — NixOS Configuration
#
# Use case: Full NixOS system configuration, optionally with home-manager.
# Framework: flake-parts (modern standard)
#
# Before using this template:
#   1. Set `hostname` in nixosConfigurations (match `networking.hostName` in config)
#   2. Set `username` for home-manager if applicable
#   3. Verify nixpkgs channel for your stability requirements
#   4. Review purity-and-hermetics.md before adding inputs
#
{
  description = "REPLACE_ME: NixOS system configuration";

  # ──────────────────────────────────────────────────────────────────────────────
  # Inputs
  # ──────────────────────────────────────────────────────────────────────────────
  inputs = {
    # Primary nixpkgs channel. Choose one:
    #   nixos-unstable — rolling release, newest packages
    #   nixos-24.11    — stable release (verify current via nixos-tools flakehub_search)
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Home Manager — manages user dotfiles and user-level services.
    # `follows` ensures home-manager uses the same nixpkgs as the system.
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs"; # REQUIRED: prevents duplicate nixpkgs
    };

    flake-parts.url = "github:hercules-ci/flake-parts";
    systems.url     = "github:nix-systems/default";

    # Optional additional inputs — verify URLs via nixos-tools `flakehub_search`:
    # sops-nix = {
    #   url = "github:Mic92/sops-nix";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };
    # disko = {
    #   url = "github:nix-community/disko";
    #   inputs.nixpkgs.follows = "nixpkgs";
    # };
  };

  # ──────────────────────────────────────────────────────────────────────────────
  # Outputs
  # ──────────────────────────────────────────────────────────────────────────────
  outputs = inputs @ { flake-parts, nixpkgs, home-manager, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {

      systems = import inputs.systems;

      # ────────────────────────────────────────────────────────────────────────
      # perSystem — dev tooling, checks, formatter
      # ────────────────────────────────────────────────────────────────────────
      perSystem = { pkgs, ... }: {
        # Format all .nix files with `nix fmt`
        formatter = pkgs.nixfmt-rfc-style;

        # devShell for working on this configuration repo itself
        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.git
            pkgs.nixfmt-rfc-style
            # pkgs.sops          # if using sops-nix
            # pkgs.age           # if using sops-nix with age keys
          ];
          shellHook = ''
            echo "NixOS config devShell ready"
          '';
        };

        checks = {
          # Example: lint all Nix files
          # nix-fmt-check = pkgs.runCommand "nix-fmt-check" {} ''
          #   ${pkgs.nixfmt-rfc-style}/bin/nixfmt --check ${./.}
          #   touch $out
          # '';
        };
      };

      # ────────────────────────────────────────────────────────────────────────
      # flake — system-level outputs (non-system-scoped)
      # ────────────────────────────────────────────────────────────────────────
      flake = {

        # ── NixOS System Configurations ───────────────────────────────────────
        # One entry per managed host. Key must match the hostname.
        # Add additional hosts by duplicating this block.
        nixosConfigurations = {

          "REPLACE_HOSTNAME" = nixpkgs.lib.nixosSystem {
            # specialArgs: values passed to all modules as extra arguments
            specialArgs = { inherit inputs; };

            modules = [
              # Core hardware/boot configuration (generated by nixos-generate-config)
              ./hosts/REPLACE_HOSTNAME/hardware-configuration.nix

              # Primary system configuration
              ./hosts/REPLACE_HOSTNAME/configuration.nix

              # Own NixOS modules (optional)
              # self.nixosModules.myModule

              # Home Manager as a NixOS module (system-managed user config)
              home-manager.nixosModules.home-manager
              {
                home-manager = {
                  useGlobalPkgs    = true;  # use system pkgs — avoids second nixpkgs eval
                  useUserPackages  = true;  # install HM packages into user profile
                  extraSpecialArgs = { inherit inputs; };
                  users = {
                    "REPLACE_USERNAME" = import ./homes/REPLACE_USERNAME.nix;
                    # Add more users here
                  };
                };
              }

              # Optional: sops-nix secret management
              # sops-nix.nixosModules.sops

              # Optional: disko declarative disk partitioning
              # disko.nixosModules.disko
            ];
          };

        };

        # ── Reusable NixOS Modules ────────────────────────────────────────────
        # Expose modules for consumption by other flakes.
        nixosModules = {
          # default = ./modules;
          # myService = ./modules/my-service.nix;
        };

        # ── Overlays ──────────────────────────────────────────────────────────
        overlays = {
          # default = final: prev: {
          #   my-custom-package = final.callPackage ./pkgs/my-custom-package {};
          # };
        };

      };
    };
}
